// <auto-generated/>
#pragma warning disable CS0618
using KiotaBlazorBug.Client.Models;
using KiotaBlazorBug.Client.Pet.FindByStatus;
using KiotaBlazorBug.Client.Pet.FindByTags;
using KiotaBlazorBug.Client.Pet.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaBlazorBug.Client.Pet
{
    /// <summary>
    /// Builds and executes requests for operations under \pet
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PetRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The findByStatus property</summary>
        public global::KiotaBlazorBug.Client.Pet.FindByStatus.FindByStatusRequestBuilder FindByStatus
        {
            get => new global::KiotaBlazorBug.Client.Pet.FindByStatus.FindByStatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The findByTags property</summary>
        public global::KiotaBlazorBug.Client.Pet.FindByTags.FindByTagsRequestBuilder FindByTags
        {
            get => new global::KiotaBlazorBug.Client.Pet.FindByTags.FindByTagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the KiotaBlazorBug.Client.pet.item collection</summary>
        /// <param name="position">ID of pet to return</param>
        /// <returns>A <see cref="global::KiotaBlazorBug.Client.Pet.Item.WithPetItemRequestBuilder"/></returns>
        public global::KiotaBlazorBug.Client.Pet.Item.WithPetItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("petId", position);
                return new global::KiotaBlazorBug.Client.Pet.Item.WithPetItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaBlazorBug.Client.Pet.PetRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PetRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pet", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaBlazorBug.Client.Pet.PetRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PetRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pet", rawUrl)
        {
        }
        /// <summary>
        /// Add a new pet to the store
        /// </summary>
        /// <returns>A <see cref="global::KiotaBlazorBug.Client.Models.Pet"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KiotaBlazorBug.Client.Models.Pet?> PostAsync(global::KiotaBlazorBug.Client.Models.Pet body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KiotaBlazorBug.Client.Models.Pet> PostAsync(global::KiotaBlazorBug.Client.Models.Pet body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::KiotaBlazorBug.Client.Models.Pet>(requestInfo, global::KiotaBlazorBug.Client.Models.Pet.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update an existing pet by Id
        /// </summary>
        /// <returns>A <see cref="global::KiotaBlazorBug.Client.Models.Pet"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KiotaBlazorBug.Client.Models.Pet?> PutAsync(global::KiotaBlazorBug.Client.Models.Pet body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KiotaBlazorBug.Client.Models.Pet> PutAsync(global::KiotaBlazorBug.Client.Models.Pet body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::KiotaBlazorBug.Client.Models.Pet>(requestInfo, global::KiotaBlazorBug.Client.Models.Pet.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Add a new pet to the store
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::KiotaBlazorBug.Client.Models.Pet body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::KiotaBlazorBug.Client.Models.Pet body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Update an existing pet by Id
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::KiotaBlazorBug.Client.Models.Pet body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::KiotaBlazorBug.Client.Models.Pet body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::KiotaBlazorBug.Client.Pet.PetRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KiotaBlazorBug.Client.Pet.PetRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KiotaBlazorBug.Client.Pet.PetRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
