// <auto-generated/>
#pragma warning disable CS0618
using KiotaBlazorBug.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaBlazorBug.Client.Pet.Item.UploadImage
{
    /// <summary>
    /// Builds and executes requests for operations under \pet\{petId}\uploadImage
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UploadImageRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaBlazorBug.Client.Pet.Item.UploadImage.UploadImageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UploadImageRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pet/{petId}/uploadImage{?additionalMetadata*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaBlazorBug.Client.Pet.Item.UploadImage.UploadImageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UploadImageRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pet/{petId}/uploadImage{?additionalMetadata*}", rawUrl)
        {
        }
        /// <summary>
        /// uploads an image
        /// </summary>
        /// <returns>A <see cref="global::KiotaBlazorBug.Client.Models.ApiResponse"/></returns>
        /// <param name="body">Binary request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KiotaBlazorBug.Client.Models.ApiResponse?> PostAsync(Stream body, Action<RequestConfiguration<global::KiotaBlazorBug.Client.Pet.Item.UploadImage.UploadImageRequestBuilder.UploadImageRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KiotaBlazorBug.Client.Models.ApiResponse> PostAsync(Stream body, Action<RequestConfiguration<global::KiotaBlazorBug.Client.Pet.Item.UploadImage.UploadImageRequestBuilder.UploadImageRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::KiotaBlazorBug.Client.Models.ApiResponse>(requestInfo, global::KiotaBlazorBug.Client.Models.ApiResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Binary request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Stream body, Action<RequestConfiguration<global::KiotaBlazorBug.Client.Pet.Item.UploadImage.UploadImageRequestBuilder.UploadImageRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Stream body, Action<RequestConfiguration<global::KiotaBlazorBug.Client.Pet.Item.UploadImage.UploadImageRequestBuilder.UploadImageRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetStreamContent(body, "application/octet-stream");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::KiotaBlazorBug.Client.Pet.Item.UploadImage.UploadImageRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KiotaBlazorBug.Client.Pet.Item.UploadImage.UploadImageRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KiotaBlazorBug.Client.Pet.Item.UploadImage.UploadImageRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// uploads an image
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UploadImageRequestBuilderPostQueryParameters 
        {
            /// <summary>Additional Metadata</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("additionalMetadata")]
            public string? AdditionalMetadata { get; set; }
#nullable restore
#else
            [QueryParameter("additionalMetadata")]
            public string AdditionalMetadata { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
